DECLARE	@YEAR		INT		=	2015
DECLARE	@FROMDATE	DATE	=	DATEFROMPARTS(@YEAR,		1, 1)
DECLARE	@TODATE		DATE	=	DATEFROMPARTS(@YEAR + 1,	1, 1)

SELECT
		YEAR(AXM.ENTRYDATE)
	,	COUNT(*)
FROM
		AXMEVENTLOG AXM
WHERE
		1 = 1
	--AND	BJH.CREATEDDATETIME BETWEEN @FROMDATE AND @TODATE
GROUP BY
		YEAR(AXM.ENTRYDATE)