DECLARE	@YEAR		INT		=	2015
DECLARE	@FROMDATE	DATE	=	DATEFROMPARTS(@YEAR,		1, 1)
DECLARE	@TODATE		DATE	=	DATEFROMPARTS(@YEAR + 1,	1, 1)



SELECT
		YEAR(INB.ALERTCREATEDDATETIME)
	,	COUNT(*)
	,	SUM(DATALENGTH(EID.DATA))
FROM
		EVENTINBOX INB
LEFT OUTER JOIN
		EVENTINBOXDATA EID
	ON	EID.INBOXID = INB.INBOXID
WHERE
		1 = 1
GROUP BY
		YEAR(INB.ALERTCREATEDDATETIME)




SELECT
		YEAR(CUD.CREATEDDATETIME)
	,	COUNT(*)
	,	SUM(DATALENGTH(CUD.DATA))
FROM
		EVENTCUD CUD
WHERE
		1 = 1
GROUP BY
		YEAR(CUD.CREATEDDATETIME)