DECLARE	@YEAR		INT		=	2015
DECLARE	@FROMDATE	DATE	=	DATEFROMPARTS(@YEAR,		1, 1)
DECLARE	@TODATE		DATE	=	DATEFROMPARTS(@YEAR + 1,	1, 1)

SELECT
		CAS.CREATEDTRANSACTIONID
	,	COUNT(*)
FROM
		INC_CUSTVENDACCOUNTSTATEMENTINTTMP CAS
WHERE
		1 = 1
	--AND	BJH.CREATEDDATETIME BETWEEN @FROMDATE AND @TODATE
GROUP BY
		CAS.CREATEDTRANSACTIONID
ORDER BY
		COUNT(*) DESC


--SELECT
--		YEAR(CAS.TRANSDATE)
--	,	COUNT(*)
--FROM
--		INC_CUSTVENDACCOUNTSTATEMENTINTTMP CAS
--WHERE
--		1 = 1
--	--AND	BJH.CREATEDDATETIME BETWEEN @FROMDATE AND @TODATE
--GROUP BY
--		YEAR(CAS.TRANSDATE)
