--USE [MicrosoftDynamicsAX]
--GO
 
--/****** Object:  StoredProcedure [dbo].[aci_CleanupBatchHistory]    Script Date: 6/12/2025 11:14:01 AM ******/
--SET ANSI_NULLS ON
--GO
 
--SET QUOTED_IDENTIFIER ON
--GO
 
---- =============================================
---- Author:		Shameera
---- Create date: 12/6/2025
---- Description:	Cleanup batchHistory table
---- =============================================
--ALTER PROCEDURE [dbo].[ACI_CleanupBatchHistory] 
--AS
DECLARE	@EARLIESTYEAR		INT

SELECT	@EARLIESTYEAR		=	MIN(YEAR(CAST([CREATEDDATETIME] AS DATE)))
FROM	BATCHHISTORY
WHERE	YEAR(CREATEDDATETIME) < 2025

DECLARE	@FROMDATE	DATE	=	DATEFROMPARTS(@EARLIESTYEAR, 1, 1)
DECLARE	@TODATE		DATE	=	DATEFROMPARTS(@EARLIESTYEAR, 1, 1)

BEGIN
	SET	NOCOUNT	ON

	BEGIN TRANSACTION

	BEGIN TRY

		DELETE
		FROM	BATCHHISTORY
		WHERE	CREATEDDATETIME BETWEEN @FROMDATE AND @TODATE

		COMMIT	TRANSACTION

		PRINT	'Records deleted successfully'

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION

		THROW

	END CATCH

END
GO


DECLARE	@YEAR		INT		=	2016
DECLARE	@FROMDATE	DATE	=	DATEFROMPARTS(@YEAR,		1, 1)
DECLARE	@TODATE		DATE	=	DATEFROMPARTS(@YEAR + 1,	1, 1)

SELECT
		COUNT(*)
FROM
		BATCHCONSTRAINTSHISTORY CNS
INNER JOIN
		BATCHHISTORY HIS
	ON	HIS.RECID = CNS.BATCHID
INNER JOIN
		BATCHJOBHISTORY BJH
	ON	BJH.RECID = HIS.BATCHJOBHISTORYID
WHERE
		1 = 1
	AND	BJH.CREATEDDATETIME BETWEEN @FROMDATE AND @TODATE