SELECT
		VNX.ACCOUNTNUM
	,	DIR.NAME
	,	VNX.TRANSDATE
	,	VNX.AMOUNTMST
	,	VNX.DUEDATE
	,	VNX.TRANSTYPE
FROM
		VENDTRANS VNX
INNER JOIN
		VENDTABLE VND
	ON	VND.PARTITION = VNX.PARTITION
	AND	VND.DATAAREAID = VNX.DATAAREAID
	AND	VND.ACCOUNTNUM = VNX.ACCOUNTNUM
LEFT OUTER JOIN
		DIRPARTYTABLE DIR
	ON	DIR.PARTITION = VND.PARTITION
	AND	DIR.RECID = VND.PARTY
WHERE
		1 = 1
	AND	VNX.DATAAREAID = '71'
	AND	VNX.ACCOUNTNUM IN ('000011253', '000011256', '000011238', 'RM2000025')