SELECT
		TXT.NAME
	,	ITX.ITEMID
	,	TRANSTYPE	=	CASE	ITO.REFERENCECATEGORY
						WHEN	0	THEN	'Sales'
						WHEN	2	THEN	'Production'
						WHEN	3	THEN	'Purch'
						WHEN	4	THEN	'InventTransaction'
						WHEN	5	THEN	'InventLossProfit'
						WHEN	6	THEN	'InventTransfer'
						WHEN	7	THEN	'SummedUp'
						WHEN	8	THEN	'ProdLine'
						WHEN	9	THEN	'BOMLine'
						WHEN	10	THEN	'BOMMain'
						WHEN	11	THEN	'WMSOrder'
						WHEN	12	THEN	'Project'
						WHEN	13	THEN	'InventCounting'
						WHEN	14	THEN	'WMSTransport'
						WHEN	15	THEN	'QuarantineOrder'
						WHEN	20	THEN	'Asset'
						WHEN	21	THEN	'TransferOrderShip'
						WHEN	22	THEN	'TransferOrderReceive'
						WHEN	23	THEN	'TransferOrderScrap'
						WHEN	24	THEN	'SalesQuotation'
						WHEN	25	THEN	'QualityOrder'
						WHEN	26	THEN	'Blocking'
						WHEN	27	THEN	'KanbanJobProcess'
						WHEN	28	THEN	'KanbanJobTransferReceipt'
						WHEN	29	THEN	'KanbanJobTransferIssue'
						WHEN	30	THEN	'KanbanJobPickingList'
						WHEN	31	THEN	'KanbanJobWIP'
						WHEN	32	THEN	'KanbanEmptied'
						WHEN	100	THEN	'PmfProdCoBy'
						WHEN	101	THEN	'ProdRelease_RU'
						WHEN	102	THEN	'FixedAssets_RU'
						WHEN	150	THEN	'Statement'
						WHEN	103	THEN	'Assembling_JP'
						WHEN	201	THEN	'WHSWork'
						WHEN	202	THEN	'WHSQuarantine'
						WHEN	203	THEN	'WHSContainer'
						ELSE				'Unknown'
						END
	,	ITX.STATUSISSUE
	,	ITX.STATUSRECEIPT
	,	ITX.DATESTATUS
	,	ITX.DATEEXPECTED
	,	ITX.DATEPHYSICAL
	,	ITX.DATEFINANCIAL
	--,	ITX.DATEINVENT
	--,	ITX.DATECLOSED
	,	ITX.QTY
	,	COSTAMOUNT	=	CASE ITX.COSTAMOUNTPOSTED + ITX.COSTAMOUNTADJUSTMENT WHEN 0 THEN ITX.COSTAMOUNTPHYSICAL ELSE ITX.COSTAMOUNTPOSTED + ITX.COSTAMOUNTADJUSTMENT END
	,	ITX.COSTAMOUNTPHYSICAL
	,	ITX.COSTAMOUNTPOSTED
	,	ITX.COSTAMOUNTADJUSTMENT
	,	ITX.COSTAMOUNTOPERATIONS
FROM
		ECORESPRODUCT PRD
INNER JOIN
		INVENTTABLE ITM
	ON	ITM.PRODUCT = PRD.RECID
LEFT OUTER JOIN
		ECORESPRODUCTTRANSLATION TXT
	ON	TXT.PRODUCT = PRD.RECID
LEFT OUTER JOIN
		INVENTTRANS ITX
	ON	ITX.PARTITION = ITM.PARTITION
	AND	ITX.DATAAREAID = ITM.DATAAREAID
	AND	ITX.ITEMID = ITM.ITEMID
LEFT OUTER JOIN
		INVENTTRANSORIGIN ITO
	ON	ITO.PARTITION = ITX.PARTITION
	AND	ITO.DATAAREAID  = ITX.DATAAREAID
	AND	ITO.RECID = ITX.INVENTTRANSORIGIN
WHERE
		1 = 1
	AND	ITM.ITEMID = '01080100017'
	AND	ITM.DATAAREAID = '71'
	AND	TXT.LANGUAGEID = 'EN-US'
	--AND	ITX.STATUSRECEIPT = 5
ORDER BY
		ITX.DATESTATUS DESC