SELECT
		BTH.BUDGETMODELID
	,	DIM.DISPLAYVALUE
	,	BTL.[DATE]
	,	BTL.ACCOUNTINGCURRENCYAMOUNT
	,	BTL.COMMENT_
	,	BTH.BUDGETMODELDATAAREAID
FROM
		BUDGETTRANSACTIONLINE BTL
INNER JOIN
		BUDGETTRANSACTIONHEADER BTH
	ON	BTH.[PARTITION] = BTL.[PARTITION]
	AND	BTH.RECID = BTL.BUDGETTRANSACTIONHEADER
LEFT OUTER JOIN
		DIMENSIONATTRIBUTEVALUECOMBINATION DIM
	ON	DIM.RECID = BTL.LEDGERDIMENSION
WHERE
		1 = 1
	AND	BTL.[DATE] BETWEEN '2024-01-01' AND '2025-12-31'